version: "3"
networks:
  app-network:
    driver: bridge
services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DATABASE: "${DB_DATABASE}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    networks:
      - app-network
  app:
    image: tungduy/tokenize-api:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      PORT: ${PORT}
    ports:
      - "${PORT}:5000"
    volumes:
      - ./app:/usr/app
    deploy:
      resources: # Set these values when you know what you do!
        limits:
          cpus: "0.001"
          memory: 50M
        reservations:
          cpus: "0.0001"
          memory: 20M
    command: bash -c "./wait-for-it.sh db:5432 -- sequelize db:migrate && npm start"
    networks:
      - app-network
  web:
    image: tungduy/tokenize-web:latest
    depends_on:
      - app
    volumes:
      - ./web:/usr/app
      - ./web/src:/usr/app/src
    command: bash -c "./wait-for-it.sh app:5000 -- npm start"
    ports:
      - "80:3000"
    networks:
      - app-network
