export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const CHECK_AUTHENTICATE = "CHECK_AUTHENTICATE";

export default {
  REQUEST_LOGIN,
  RECEIVE_LOGIN
};
