version: "3"
services:
  db:
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DATABASE: "${DB_DATABASE}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
  web:
    images: tungduy/tokenize-api:latest
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      PORT: ${PORT}
    volumes:
      - ./:/usr/app
    command: bash -c "./wait-for-it.sh db:5432 -- npm start"
