export const REQUEST_ALL_CART = "REQUEST_ALL_CART";
export const RECEIVE_ALL_CART = "RECEIVE_ALL_CART";
export const ADD_TO_CART = "ADD_TO_CART";

export default {
  REQUEST_ALL_CART,
  RECEIVE_ALL_CART,
  ADD_TO_CART
};
